services:
  spotiflac:
    image: spotiflac-docker-vpn:latest
    container_name: spotiflac
    pull_policy: never
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TZ=Europe/Berlin
      - OUTPUT_DIR=/downloads
      - PORT=5000
      - UI_PASSWORD=
      - VPN_USER=
      - VPN_PASS=
      - VPN_CONFIG_FILE=/vpn/config.ovpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 5000:5000
    volumes:
      - /mnt/smb_share/Musik/tagged:/downloads
      - spotiflac_config:/vpn
    restart: unless-stopped

volumes:
  spotiflac_config:
    external: true
